version: '3'
services:
 db:
   image: mysql:latest
   container_name: mysql
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=nf5*AHfGexv4O~LVT_[?Ku<Pm)Qk
     - MYSQL_DATABASE=pinkFlamingosDatabase
   volumes:
     - /Users/sirbia/Desktop/mysql/db:/var/lib/mysql 