version: '3'
services:
 db:
   image: mysql:latest
   container_name: mysql
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=Happ1n3ss
     - MYSQL_DATABASE=pinkFlamingosDatabase
   volumes:
     - /Users/sirbia/Desktop/mysql/db:/var/lib/mysql 